In [ ]:
!pip install --pre --extra-index https://pypi.anaconda.org/scipy-wheels-nightly/simple scikit-learn

Looking in indexes: https://pypi.org/simple, https://pypi.anaconda.org/scipy-wheels-nightly/simple


In [ ]:
!git clone git://github.com/scikit-learn/scikit-learn.git

Cloning into 'scikit-learn'...
remote: Enumerating objects: 198843, done.
remote: Counting objects: 100% (1174/1174), done.
remote: Compressing objects: 100% (756/756), done.
remote: Total 198843 (delta 598), reused 799 (delta 417), pack-reused 197669
Receiving objects: 100% (198843/198843), 123.42 MiB | 25.25 MiB/s, done.
Resolving deltas: 100% (150045/150045), done.


In [ ]:
%cd scikit-learn

/content/scikit-learn


In [ ]:
!pip install cython

In [ ]:
!pip install --verbose --no-build-isolation --editable .

In [1]:
!python -c "import sklearn; sklearn.show_versions()"


System:
    python: 3.7.10 (default, May  3 2021, 02:48:31)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic

Python dependencies:
       pip: 19.3.1
setuptools: 57.0.0
   sklearn: 0.22.2.post1
     numpy: 1.19.5
     scipy: 1.4.1
    Cython: 0.29.23
    pandas: 1.1.5
matplotlib: 3.2.2
    joblib: 1.0.1

Built with OpenMP: True


# Note :

sklearnの古いバージョン　0.22.2が入っているので、こいつをまずアンインストールする必要がある。

In [2]:
!pip uninstall -y scikit-learn
!pip install --pre --extra-index https://pypi.anaconda.org/scipy-wheels-nightly/simple scikit-learn

Uninstalling scikit-learn-0.22.2.post1:
  Successfully uninstalled scikit-learn-0.22.2.post1
Looking in indexes: https://pypi.org/simple, https://pypi.anaconda.org/scipy-wheels-nightly/simple
     |████████████████████████████████| 22.9MB 129kB/s 


In [4]:
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold

In [5]:
X = np.ones((17, 2))
y = np.array([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
groups = np.array([1, 1, 2, 2, 3, 3, 3, 4, 5, 5, 5, 5, 6, 6, 7, 8, 8])
cv = StratifiedGroupKFold(n_splits=3)
for train_idxs, test_idxs in cv.split(X, y, groups):
     print("TRAIN:", groups[train_idxs])
     print("      ", y[train_idxs])
     print(" TEST:", groups[test_idxs])
     print("      ", y[test_idxs])

TRAIN: [1 1 2 2 4 5 5 5 5 8 8]
       [0 0 1 1 1 0 0 0 0 0 0]
 TEST: [3 3 3 6 6 7]
       [1 1 1 0 0 0]
TRAIN: [3 3 3 4 5 5 5 5 6 6 7]
       [1 1 1 1 0 0 0 0 0 0 0]
 TEST: [1 1 2 2 8 8]
       [0 0 1 1 0 0]
TRAIN: [1 1 2 2 3 3 3 6 6 7 8 8]
       [0 0 1 1 1 1 1 0 0 0 0 0]
 TEST: [4 5 5 5 5]
       [1 0 0 0 0]
